Do not schedule project import when migrating using GitLab Migration
  - When migrating projects using GitLab Migration an exception is raised
    NoMethodError undefined method `start_with?` that is caused by
    Projects::CreateService
  - Fix this bug by not scheduling project import in this case

Changelog: fixed