Namespace the Gitlab constant to avoid NameError
By looking at a Review App migrations job, I noticed that when the
license failed to be created, the following NameError was thrown:

```
NameError: uninitialized constant Tasks::Gitlab::License
Did you mean? Licenses

/srv/gitlab/ee/lib/tasks/gitlab/license.rake:65:in `rescue in seed_license'
/srv/gitlab/ee/lib/tasks/gitlab/license.rake:62:in `seed_license'
/srv/gitlab/ee/lib/tasks/gitlab/license.rake:23:in `block (3 levels) in initialize'
```

Namespacing the consstant solves this.

This line was introduced in
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/85524.

Changelog: fixed
Signed-off-by: Rémy Coutable <remy@rymai.me>